//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.DateTime data { get; set; }
        public int type { get; set; }
        public string message { get; set; }
        public string user { get; set; }
        public string IP { get; set; }
        public string request { get; set; }
        public string user_agent { get; set; }
    
        public virtual LogType LogType { get; set; }
    }
}
