//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunita
    {
        public long id { get; set; }
        public int idAzione { get; set; }
        public long idOsservazione { get; set; }
        public int idIndicazione { get; set; }
        public string idBacteria { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public bool cancellato { get; set; }
    
        public virtual Azione Azione { get; set; }
        public virtual Bacteria Bacteria { get; set; }
        public virtual Indicazione Indicazione { get; set; }
        public virtual Osservazione Osservazione { get; set; }
    }
}
