//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osservazione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Osservazione()
        {
            this.Opportunita = new HashSet<Opportunita>();
        }
    
        public long id { get; set; }
        public int idScheda { get; set; }
        public int numOperatori { get; set; }
        public int idOperatore { get; set; }
        public Nullable<bool> operatoreEsterno { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opportunita> Opportunita { get; set; }
        public virtual Scheda Scheda { get; set; }
        public virtual Operatore Operatore { get; set; }
    }
}
