//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scheda()
        {
            this.Osservazione = new HashSet<Osservazione>();
        }
    
        public int id { get; set; }
        public int durataSessione { get; set; }
        public int idReparto { get; set; }
        public int idWebServiceReparto { get; set; }
        public int idUtente { get; set; }
        public string note { get; set; }
        public int idStatoSessione { get; set; }
        public System.DateTime data { get; set; }
        public System.DateTime dataInserimento { get; set; }
        public System.DateTime dataUltimaModificaStato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osservazione> Osservazione { get; set; }
        public virtual StatoSessione StatoSessione { get; set; }
        public virtual Utente Utente { get; set; }
    }
}
