//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipologiaStruttura
    {
        public string CodTipologia { get; set; }
        public string Descrizione { get; set; }
        public string TipoEnte { get; set; }
        public bool IsAttivo { get; set; }
        public int Ordinale { get; set; }
        public Nullable<int> CodAreaDisciplina { get; set; }
    }
}
