//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UltimaPosizione
    {
        public int id { get; set; }
        public string username { get; set; }
        public string url { get; set; }
        public string datiRicerca { get; set; }
        public System.DateTime data { get; set; }
    }
}
