//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtenteStruttura
    {
        public int ID { get; set; }
        public int idUtente { get; set; }
        public string codRegione { get; set; }
        public string codAzienda { get; set; }
        public Nullable<int> idStrutturaErogatrice { get; set; }
        public Nullable<int> idWebServiceStruttura { get; set; }
        public Nullable<int> idReparto { get; set; }
        public Nullable<int> idWebServiceReparto { get; set; }
        public System.DateTime dataDal { get; set; }
        public Nullable<System.DateTime> dataAl { get; set; }
    
        public virtual Utente Utente { get; set; }
    }
}
