//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtenteDaCensire
    {
        public int Id { get; set; }
        public string CodiceFiscale { get; set; }
        public string CodRegione { get; set; }
        public string CodAzienda { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public bool Pubblico { get; set; }
        public int IdRuolo { get; set; }
        public int IdStato { get; set; }
        public System.DateTime DataCandidatura { get; set; }
        public string KeyStruttura { get; set; }
        public string IndirizzoIPCandidatura { get; set; }
        public Nullable<System.DateTime> DataInvioServiceDesk { get; set; }
        public Nullable<System.DateTime> DataProfilazione { get; set; }
    
        public virtual Ruoli Ruoli { get; set; }
        public virtual StatoCandidatura StatoCandidatura { get; set; }
    }
}
