//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAzienda
    {
        public string CodRegione { get; set; }
        public string CodAzienda { get; set; }
        public string Denominazione { get; set; }
        public System.DateTime DataInizio { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public string KeyAzienda { get; set; }
    }
}
