//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTipoAnagrafeRegionale
    {
        public string CodTipoAnagrafeRegionale { get; set; }
        public System.DateTime DataInizio { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public string Descrizione { get; set; }
        public int CodMacroArea { get; set; }
        public Nullable<int> CodTarget { get; set; }
        public string CodTipoStrutturaMinisteriale { get; set; }
        public string CodTipoStrutturaMinistarialeInterna { get; set; }
    }
}
