//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Candidatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utente()
        {
            this.UtenteStruttura = new HashSet<UtenteStruttura>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string email { get; set; }
        public int idRuolo { get; set; }
        public bool attivato { get; set; }
        public bool cancellato { get; set; }
        public string CodiceFiscale { get; set; }
    
        public virtual Ruoli Ruoli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtenteStruttura> UtenteStruttura { get; set; }
    }
}
