//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Candidatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAreaDisciplina
    {
        public int CodAreaDisciplina { get; set; }
        public string Nome { get; set; }
        public string Descrizione { get; set; }
        public int Ordinale { get; set; }
    }
}
