//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Candidatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwReparto
    {
        public int IdWebServiceReparto { get; set; }
        public int IdReparto { get; set; }
        public string KeyReparto { get; set; }
        public int IdStrutturaErogatrice { get; set; }
        public System.DateTime DataRiferimentoStruttura { get; set; }
        public int idWebServiceStruttura { get; set; }
        public string keyStruttura { get; set; }
        public string keyStrutturaData { get; set; }
        public System.DateTime DataInizio { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public string NomeOriginale { get; set; }
        public string Nome { get; set; }
        public string Descrizione { get; set; }
        public string CodDisciplina { get; set; }
        public string ProgressivoDivisione { get; set; }
        public string CodRegione { get; set; }
        public string CodAzienda { get; set; }
        public string CodiceTipologiaStruttura { get; set; }
        public string CodTipoAnagrafeRegionale { get; set; }
        public Nullable<int> codAreaDisciplina { get; set; }
        public Nullable<bool> Cancellato { get; set; }
        public int Stato { get; set; }
    }
}
