//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Candidatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStruttura
    {
        public int idWebServiceStruttura { get; set; }
        public int IdStrutturaErogatrice { get; set; }
        public System.DateTime DataRiferimentoStruttura { get; set; }
        public string KeyStruttura { get; set; }
        public string KeyStrutturaData { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public System.DateTime DataApertura { get; set; }
        public Nullable<System.DateTime> DataChiusura { get; set; }
        public string Denominazione { get; set; }
        public string DenominazioneOriginale { get; set; }
        public string CodRegione { get; set; }
        public string CodAzienda { get; set; }
        public System.DateTime DataInizioAzienda { get; set; }
        public string CodMin { get; set; }
        public string SubCodMin { get; set; }
        public int IdCodStruttura { get; set; }
        public string CodTipoAnagrafeRegionale { get; set; }
        public string CodiceTipologiaStruttura { get; set; }
        public string CodTipoStrutturaMinisteriale { get; set; }
        public int CodMacroArea { get; set; }
        public System.DateTime DataInizioTipoAnagrafeRegionale { get; set; }
        public string PubblicoPrivato { get; set; }
        public Nullable<bool> isPrivata { get; set; }
        public string Indirizzo { get; set; }
        public string CapAggiuntivo { get; set; }
        public int IdStrutturaFisica { get; set; }
        public System.DateTime DataInizioStrutturaFisica { get; set; }
        public System.DateTime TimeStampIns { get; set; }
        public System.DateTime TimeStampVar { get; set; }
        public int Stato { get; set; }
        public string KeyAzienda { get; set; }
    }
}
